name: Build Geode Mod

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    continue-on-error: true # continue even if build failed for some platform
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          
        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}
      
  package:
    name: Package and release builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v3
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}

      - uses: softprops/action-gh-release@v2
        with:
          name: "Development Release"
          body: |
           Release of success build for latest commit on `${{ github.head_ref || github.ref_name }}`.
           <hr>
           The build workflow run for this release goes here:
           ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          tag_name: "nightly"
          files: "${{steps.build.outputs.build-output}}/*"
